python src/test_problem.py
python src/test_geometry.py
python src/test_graph_utils.py
python src/test_numericals.py
python src/test_graph.py
python src/test_dd.py
python src/test_ar.py
python src/test_ddar.py
python src/test_trace_back.py
python src/test_alphageometry.py
python src/test_lm_inference.py